## 예외처리, 파일조작

### 확장 멤버

- https://learn.microsoft.com/ko-kr/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

### 예외 처리(Exception)

- 프로그램 설계 시 예외 상황이 발생할 가능성이 있는 것을 예측, 사전에 예외처리 하도록한다
- 에러의 종류와 대응책

| 구분 | 문법 에러(syntax error) | 런타임 에러(runtime error) | 논리 에러(logic error) |
| --- | --- | --- | --- |
| 원인 | 코드의 형식적 오류 | 실행 중에 예상외의 사태가 발생하여 동작이 중지됨 | 기술한 처리 내용에 논리적인 오류가 있음 |
| 알아채는 방법 | 컴파일하면 에러 남 | 실행하면 도중에 강제 종료 됨 | 실행하면 예상외의 값이 나옴 |
| 해결 방법 | 컴파일러의 지적을 보고 수정 | 에러 | 원인을 스스로 찾아서 해결해야 함 |

- 예외 처리의 흐름

    ```csharp
    try 
    {
    	// error 발생할 수 있는 코드 작성
    	SomeError();
    }
    catch (Exception e)
    {
    	// Exception 이 발생했을 때 실행되는 코드
    	// 'e'는 발생한 에러에 대한 정보를 담고 있는 객체
    	
    	throw; // 예외처리를 미룸
    }
    finally 
    {
    	// 항상 해야하는 처리(switch문의 default같은 역할)
    }
    ```

- 오리지널 예외 클래스 정의

    ```csharp
    public InventoryFullException() : base("인벤토리가 가득 찼다"){ ... }
    ```

- Recap
    - 에러
        - syntax error, runtime error, logic error 의 3종류
        - 예외처리를 할 때는, runtime error를 대처한다
    - 예외의 종류
        - API에는 여러가지 예외적 상황을 표현하는 예외 클래스가 준비되어 있다.
        - 예외 클래스를 상속하여 오리지날 예외 클래스를 정의할 수 있다.
    - 예외 처리
        - try-catch 문을 사용하면, try 블록 내에 예외가 발생했을 때 catch 블록에서 처리가 옮겨진다
        - finally 블록으로 나중에 꼭 해야하는 처리를 할 수 있다
        - throw 문을 사용하면 임의로 예외를 발생시킬 수 있다

### Null 처리 하기

```csharp
public MyException(string? message) : base(message ?? "알수없는 에러 발생") { ... }
```

- `string?` → *nullable reference type* (null 허용)
    - `string message` → null을 허용하지 않음 (컴파일러 경고 발생 가능)
    - `string? message` → null을 허용
- `??` → 널 병합 연산자: *null-coalescing operator* (널이면 오른쪽 값 사용)
    - **역할:** 왼쪽 피연산자가 `null` 이면 오른쪽 값을 반환, `null` 이 아니면 왼쪽 값을 그대로 반환.

### 파일 조작

```csharp
string text = "hello world";

try
{
    // 파일 쓰기: 덮어쓰기
    System.IO.File.WriteAllText("downloads/test.txt", text); // 경로+파일.확장자, 내용
    
    // 파일 쓰기: 추가하기
    System.IO.File.AppendAllText("downloads/test.txt", text);
		
    // 파일 읽어오기
    string[] lines = System.IO.File.ReadAllLines("downloads/text.txt");
    lines.ToList().ForEach(Console.WriteLine);
}
catch (FileNotFoundException e)
{
    Console.WriteLine("파일이 없습니다");
}
catch (Exception e)
{
    Console.WriteLine($"다른 예외 발생: {e.Message}");
}
```